using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

public class FormMonitor : Form
{
    private IContainer icontainer_0;
    private GroupBox groupBox_0;
    private Label label109;
    private Label label60;
    private Label label108;
    private Label RepairableItems;
    private Label label57;
    private Label ShopCafeItems;
    private Label label107;
    private Label label54;
    private Label RegisteredShopItems;
    private Label VipUsers;
    private Label label101;
    private Label label2;
    private Label label102;
    private Label label104;
    private Label lebl106;
    private Label label105;
    private Label label103;
    private Label label18;
    private Label label19;
    private Label label21;
    private Label TotalClans;
    private Label label24;
    private Label UnknownUsers;
    private Label label27;
    private Label RegisteredUsers;
    private Label OnlinePlayers;
    private Label TotalBannedPlayers;
    private Timer timer_0;

    public FormMonitor()
    {
        this.InitializeComponent();
    }

    private void FormMonitor_Load(object sender, EventArgs e)
    {
        float num = float.Parse("10") / 100f;
        this.BackgroundImage = GClass5.smethod_0().method_0(Class11.Bitmap_0, num);
        this.BackgroundImageLayout = ImageLayout.Center;
        this.RegisteredUsers.Text = "Loading...";
        this.OnlinePlayers.Text = "Loading...";
        this.TotalClans.Text = "Loading...";
        this.VipUsers.Text = "Loading...";
        this.UnknownUsers.Text = "Loading...";
        this.TotalBannedPlayers.Text = "Loading...";
        this.RegisteredShopItems.Text = "Loading...";
        this.ShopCafeItems.Text = "Loading...";
        this.RepairableItems.Text = "Loading...";
        this.timer_0.Start();
    }

    private void InitializeComponent()
    {
        this.icontainer_0 = new Container();
        ComponentResourceManager manager = new ComponentResourceManager(typeof(FormMonitor));
        this.groupBox_0 = new GroupBox();
        this.label109 = new Label();
        this.label60 = new Label();
        this.label108 = new Label();
        this.RepairableItems = new Label();
        this.label57 = new Label();
        this.ShopCafeItems = new Label();
        this.label107 = new Label();
        this.label54 = new Label();
        this.RegisteredShopItems = new Label();
        this.VipUsers = new Label();
        this.label101 = new Label();
        this.label2 = new Label();
        this.label102 = new Label();
        this.label104 = new Label();
        this.lebl106 = new Label();
        this.label105 = new Label();
        this.label103 = new Label();
        this.label18 = new Label();
        this.label19 = new Label();
        this.label21 = new Label();
        this.TotalClans = new Label();
        this.label24 = new Label();
        this.UnknownUsers = new Label();
        this.label27 = new Label();
        this.RegisteredUsers = new Label();
        this.OnlinePlayers = new Label();
        this.TotalBannedPlayers = new Label();
        this.timer_0 = new Timer(this.icontainer_0);
        this.groupBox_0.SuspendLayout();
        base.SuspendLayout();
        this.groupBox_0.BackColor = Color.Transparent;
        this.groupBox_0.Controls.Add(this.label109);
        this.groupBox_0.Controls.Add(this.label60);
        this.groupBox_0.Controls.Add(this.label108);
        this.groupBox_0.Controls.Add(this.RepairableItems);
        this.groupBox_0.Controls.Add(this.label57);
        this.groupBox_0.Controls.Add(this.ShopCafeItems);
        this.groupBox_0.Controls.Add(this.label107);
        this.groupBox_0.Controls.Add(this.label54);
        this.groupBox_0.Controls.Add(this.RegisteredShopItems);
        this.groupBox_0.Controls.Add(this.VipUsers);
        this.groupBox_0.Controls.Add(this.label101);
        this.groupBox_0.Controls.Add(this.label2);
        this.groupBox_0.Controls.Add(this.label102);
        this.groupBox_0.Controls.Add(this.label104);
        this.groupBox_0.Controls.Add(this.lebl106);
        this.groupBox_0.Controls.Add(this.label105);
        this.groupBox_0.Controls.Add(this.label103);
        this.groupBox_0.Controls.Add(this.label18);
        this.groupBox_0.Controls.Add(this.label19);
        this.groupBox_0.Controls.Add(this.label21);
        this.groupBox_0.Controls.Add(this.TotalClans);
        this.groupBox_0.Controls.Add(this.label24);
        this.groupBox_0.Controls.Add(this.UnknownUsers);
        this.groupBox_0.Controls.Add(this.label27);
        this.groupBox_0.Controls.Add(this.RegisteredUsers);
        this.groupBox_0.Controls.Add(this.OnlinePlayers);
        this.groupBox_0.Controls.Add(this.TotalBannedPlayers);
        this.groupBox_0.FlatStyle = FlatStyle.Flat;
        this.groupBox_0.Font = new Font("Roboto Slab", 8f);
        this.groupBox_0.ForeColor = Color.White;
        this.groupBox_0.Location = new Point(15, 9);
        this.groupBox_0.Name = "SrvInfoGB";
        this.groupBox_0.Size = new Size(390, 0x126);
        this.groupBox_0.TabIndex = 0x59;
        this.groupBox_0.TabStop = false;
        this.groupBox_0.Text = "Database Monitor";
        this.label109.AutoSize = true;
        this.label109.Font = new Font("Roboto Slab", 10f);
        this.label109.ForeColor = Color.Silver;
        this.label109.Location = new Point(0x11, 0xfd);
        this.label109.Name = "label109";
        this.label109.Size = new Size(0x7a, 0x13);
        this.label109.TabIndex = 0x70;
        this.label109.Text = "Repairable Items";
        this.label60.AutoSize = true;
        this.label60.Font = new Font("Roboto Slab", 10f);
        this.label60.ForeColor = Color.Silver;
        this.label60.Location = new Point(0xca, 0xfd);
        this.label60.Name = "label60";
        this.label60.Size = new Size(12, 0x13);
        this.label60.TabIndex = 0x71;
        this.label60.Text = ":";
        this.label108.AutoSize = true;
        this.label108.Font = new Font("Roboto Slab", 10f);
        this.label108.ForeColor = Color.Silver;
        this.label108.Location = new Point(0x11, 0xe1);
        this.label108.Name = "label108";
        this.label108.Size = new Size(0x75, 0x13);
        this.label108.TabIndex = 0x5b;
        this.label108.Text = "Shop Cafe Items";
        this.RepairableItems.AutoSize = true;
        this.RepairableItems.Font = new Font("Roboto Slab", 10f);
        this.RepairableItems.ForeColor = Color.Silver;
        this.RepairableItems.Location = new Point(0xda, 0xfd);
        this.RepairableItems.Name = "RepairableItems";
        this.RepairableItems.Size = new Size(0x56, 0x13);
        this.RepairableItems.TabIndex = 0x72;
        this.RepairableItems.Text = "1234567890";
        this.label57.AutoSize = true;
        this.label57.Font = new Font("Roboto Slab", 10f);
        this.label57.ForeColor = Color.Silver;
        this.label57.Location = new Point(0xca, 0xe1);
        this.label57.Name = "label57";
        this.label57.Size = new Size(12, 0x13);
        this.label57.TabIndex = 0x5c;
        this.label57.Text = ":";
        this.ShopCafeItems.AutoSize = true;
        this.ShopCafeItems.Font = new Font("Roboto Slab", 10f);
        this.ShopCafeItems.ForeColor = Color.Silver;
        this.ShopCafeItems.Location = new Point(0xda, 0xe1);
        this.ShopCafeItems.Name = "ShopCafeItems";
        this.ShopCafeItems.Size = new Size(0x56, 0x13);
        this.ShopCafeItems.TabIndex = 0x5d;
        this.ShopCafeItems.Text = "1234567890";
        this.label107.AutoSize = true;
        this.label107.Font = new Font("Roboto Slab", 10f);
        this.label107.ForeColor = Color.Silver;
        this.label107.Location = new Point(0x11, 0xc5);
        this.label107.Name = "label107";
        this.label107.Size = new Size(0x9f, 0x13);
        this.label107.TabIndex = 0x58;
        this.label107.Text = "Registered Shop Items";
        this.label54.AutoSize = true;
        this.label54.Font = new Font("Roboto Slab", 10f);
        this.label54.ForeColor = Color.Silver;
        this.label54.Location = new Point(0xca, 0xc5);
        this.label54.Name = "label54";
        this.label54.Size = new Size(12, 0x13);
        this.label54.TabIndex = 0x59;
        this.label54.Text = ":";
        this.RegisteredShopItems.AutoSize = true;
        this.RegisteredShopItems.Font = new Font("Roboto Slab", 10f);
        this.RegisteredShopItems.ForeColor = Color.Silver;
        this.RegisteredShopItems.Location = new Point(0xda, 0xc5);
        this.RegisteredShopItems.Name = "RegisteredShopItems";
        this.RegisteredShopItems.Size = new Size(0x56, 0x13);
        this.RegisteredShopItems.TabIndex = 90;
        this.RegisteredShopItems.Text = "1234567890";
        this.VipUsers.AutoSize = true;
        this.VipUsers.Font = new Font("Roboto Slab", 10f);
        this.VipUsers.ForeColor = Color.Silver;
        this.VipUsers.Location = new Point(0xda, 0x71);
        this.VipUsers.Name = "VipUsers";
        this.VipUsers.Size = new Size(0x56, 0x13);
        this.VipUsers.TabIndex = 0x57;
        this.VipUsers.Text = "1234567890";
        this.label101.AutoSize = true;
        this.label101.Font = new Font("Roboto Slab", 10f);
        this.label101.ForeColor = Color.Silver;
        this.label101.Location = new Point(0x11, 0x1d);
        this.label101.Name = "label101";
        this.label101.Size = new Size(0x7b, 0x13);
        this.label101.TabIndex = 0x2c;
        this.label101.Text = "Registered Users";
        this.label2.AutoSize = true;
        this.label2.Font = new Font("Roboto Slab", 10f);
        this.label2.ForeColor = Color.Silver;
        this.label2.Location = new Point(0xca, 0x71);
        this.label2.Name = "label2";
        this.label2.Size = new Size(12, 0x13);
        this.label2.TabIndex = 0x56;
        this.label2.Text = ":";
        this.label102.AutoSize = true;
        this.label102.Font = new Font("Roboto Slab", 10f);
        this.label102.ForeColor = Color.Silver;
        this.label102.Location = new Point(0x11, 0x39);
        this.label102.Name = "label102";
        this.label102.Size = new Size(0x6b, 0x13);
        this.label102.TabIndex = 0x2d;
        this.label102.Text = "Online Players";
        this.label104.AutoSize = true;
        this.label104.Font = new Font("Roboto Slab", 10f);
        this.label104.ForeColor = Color.Silver;
        this.label104.Location = new Point(0x11, 0x71);
        this.label104.Name = "label104";
        this.label104.Size = new Size(0x4b, 0x13);
        this.label104.TabIndex = 0x55;
        this.label104.Text = "VIP Users";
        this.lebl106.AutoSize = true;
        this.lebl106.Font = new Font("Roboto Slab", 10f);
        this.lebl106.ForeColor = Color.Silver;
        this.lebl106.Location = new Point(0x11, 0xa9);
        this.lebl106.Name = "lebl106";
        this.lebl106.Size = new Size(150, 0x13);
        this.lebl106.TabIndex = 0x2f;
        this.lebl106.Text = "Total Banned Players";
        this.label105.AutoSize = true;
        this.label105.Font = new Font("Roboto Slab", 10f);
        this.label105.ForeColor = Color.Silver;
        this.label105.Location = new Point(0x11, 0x8d);
        this.label105.Name = "label105";
        this.label105.Size = new Size(0x76, 0x13);
        this.label105.TabIndex = 0x33;
        this.label105.Text = "Unknown Users";
        this.label103.AutoSize = true;
        this.label103.Font = new Font("Roboto Slab", 10f);
        this.label103.ForeColor = Color.Silver;
        this.label103.Location = new Point(0x11, 0x55);
        this.label103.Name = "label103";
        this.label103.Size = new Size(0x53, 0x13);
        this.label103.TabIndex = 0x35;
        this.label103.Text = "Total Clans";
        this.label18.AutoSize = true;
        this.label18.Font = new Font("Roboto Slab", 10f);
        this.label18.ForeColor = Color.Silver;
        this.label18.Location = new Point(0xca, 0x1d);
        this.label18.Name = "label18";
        this.label18.Size = new Size(12, 0x13);
        this.label18.TabIndex = 0x38;
        this.label18.Text = ":";
        this.label19.AutoSize = true;
        this.label19.Font = new Font("Roboto Slab", 10f);
        this.label19.ForeColor = Color.Silver;
        this.label19.Location = new Point(0xca, 0x39);
        this.label19.Name = "label19";
        this.label19.Size = new Size(12, 0x13);
        this.label19.TabIndex = 0x39;
        this.label19.Text = ":";
        this.label21.AutoSize = true;
        this.label21.Font = new Font("Roboto Slab", 10f);
        this.label21.ForeColor = Color.Silver;
        this.label21.Location = new Point(0xca, 0xa9);
        this.label21.Name = "label21";
        this.label21.Size = new Size(12, 0x13);
        this.label21.TabIndex = 0x3b;
        this.label21.Text = ":";
        this.TotalClans.AutoSize = true;
        this.TotalClans.Font = new Font("Roboto Slab", 10f);
        this.TotalClans.ForeColor = Color.Silver;
        this.TotalClans.Location = new Point(0xda, 0x55);
        this.TotalClans.Name = "TotalClans";
        this.TotalClans.Size = new Size(0x56, 0x13);
        this.TotalClans.TabIndex = 0x4d;
        this.TotalClans.Text = "1234567890";
        this.label24.AutoSize = true;
        this.label24.Font = new Font("Roboto Slab", 10f);
        this.label24.ForeColor = Color.Silver;
        this.label24.Location = new Point(0xca, 0x8d);
        this.label24.Name = "label24";
        this.label24.Size = new Size(12, 0x13);
        this.label24.TabIndex = 0x3e;
        this.label24.Text = ":";
        this.UnknownUsers.AutoSize = true;
        this.UnknownUsers.Font = new Font("Roboto Slab", 10f);
        this.UnknownUsers.ForeColor = Color.Silver;
        this.UnknownUsers.Location = new Point(0xda, 0x8d);
        this.UnknownUsers.Name = "UnknownUsers";
        this.UnknownUsers.Size = new Size(0x56, 0x13);
        this.UnknownUsers.TabIndex = 0x4b;
        this.UnknownUsers.Text = "1234567890";
        this.label27.AutoSize = true;
        this.label27.Font = new Font("Roboto Slab", 10f);
        this.label27.ForeColor = Color.Silver;
        this.label27.Location = new Point(0xca, 0x55);
        this.label27.Name = "label27";
        this.label27.Size = new Size(12, 0x13);
        this.label27.TabIndex = 0x41;
        this.label27.Text = ":";
        this.RegisteredUsers.AutoSize = true;
        this.RegisteredUsers.Font = new Font("Roboto Slab", 10f);
        this.RegisteredUsers.ForeColor = Color.Silver;
        this.RegisteredUsers.Location = new Point(0xda, 0x1d);
        this.RegisteredUsers.Name = "RegisteredUsers";
        this.RegisteredUsers.Size = new Size(0x56, 0x13);
        this.RegisteredUsers.TabIndex = 0x44;
        this.RegisteredUsers.Text = "1234567890";
        this.OnlinePlayers.AutoSize = true;
        this.OnlinePlayers.Font = new Font("Roboto Slab", 10f);
        this.OnlinePlayers.ForeColor = Color.Silver;
        this.OnlinePlayers.Location = new Point(0xda, 0x39);
        this.OnlinePlayers.Name = "OnlinePlayers";
        this.OnlinePlayers.Size = new Size(0x56, 0x13);
        this.OnlinePlayers.TabIndex = 0x45;
        this.OnlinePlayers.Text = "1234567890";
        this.TotalBannedPlayers.AutoSize = true;
        this.TotalBannedPlayers.Font = new Font("Roboto Slab", 10f);
        this.TotalBannedPlayers.ForeColor = Color.Silver;
        this.TotalBannedPlayers.Location = new Point(0xda, 0xa9);
        this.TotalBannedPlayers.Name = "TotalBannedPlayers";
        this.TotalBannedPlayers.Size = new Size(0x56, 0x13);
        this.TotalBannedPlayers.TabIndex = 0x47;
        this.TotalBannedPlayers.Text = "1234567890";
        this.timer_0.Interval = 0x3e8;
        this.timer_0.Tick += new EventHandler(this.timer_0_Tick);
        base.AutoScaleDimensions = new SizeF(7f, 15f);
        base.AutoScaleMode = AutoScaleMode.Font;
        this.BackColor = Color.FromArgb(0x2e, 0x33, 0x49);
        base.ClientSize = new Size(420, 0x139);
        base.Controls.Add(this.groupBox_0);
        this.Font = new Font("Roboto Slab", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
        base.FormBorderStyle = FormBorderStyle.None;
        base.Icon = (Icon) manager.GetObject("$this.Icon");
        base.Name = "FormMonitor";
        this.Text = "FormMonitor";
        base.Load += new EventHandler(this.FormMonitor_Load);
        this.groupBox_0.ResumeLayout(false);
        this.groupBox_0.PerformLayout();
        base.ResumeLayout(false);
    }

    override void Form.Dispose(bool disposing)
    {
        if (disposing && (this.icontainer_0 != null))
        {
            this.icontainer_0.Dispose();
        }
        base.Dispose(disposing);
    }

    private void timer_0_Tick(object sender, EventArgs e)
    {
        this.RegisteredUsers.Text = GClass9.string_5;
        this.OnlinePlayers.Text = GClass9.string_6;
        this.TotalClans.Text = GClass9.string_7;
        this.VipUsers.Text = GClass9.string_8;
        this.UnknownUsers.Text = GClass9.string_9;
        this.TotalBannedPlayers.Text = GClass9.string_10;
        this.RegisteredShopItems.Text = GClass9.string_11;
        this.ShopCafeItems.Text = GClass9.string_12;
        this.RepairableItems.Text = GClass9.string_13;
    }
}

