using Plugin.Core.Utility;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

public class FormAdditional : Form
{
    private IContainer icontainer_0;
    private GroupBox groupBox1;
    private Timer timer_0;
    private Label ServerRegion;
    private Label label118;
    private Label label28;
    private Label label112;
    private Label Label116;
    private Label label117;
    private Label ConfigIndex;
    private Label RunTimeline;
    private Label AutoBan;
    private Label label22;
    private Label RuleIndex;
    private Label label114;
    private Label label119;
    private Label label20;
    private Label InternetCafe;
    private Label label26;
    private Label AutoAccount;
    private Label label111;
    private Label label44;
    private Label label115;
    private Label label23;
    private Label label113;
    private Label label17;
    private Label label43;
    private Label LocalAddress;
    private Label ServerVersion;
    private Label label25;

    public FormAdditional()
    {
        this.InitializeComponent();
    }

    private void FormAdditional_Load(object sender, EventArgs e)
    {
        float num = float.Parse("10") / 100f;
        this.BackgroundImage = GClass5.smethod_0().method_0(Class11.Bitmap_0, num);
        this.BackgroundImageLayout = ImageLayout.Center;
        this.ServerVersion.Text = "Loading...";
        this.ServerRegion.Text = "Loading...";
        this.LocalAddress.Text = "Loading...";
        this.RunTimeline.Text = "Loading...";
        this.ConfigIndex.Text = "Loading...";
        this.RuleIndex.Text = "Loading...";
        this.InternetCafe.Text = "Loading...";
        this.AutoAccount.Text = "Loading...";
        this.AutoBan.Text = "Loading...";
        this.timer_0.Start();
    }

    private void InitializeComponent()
    {
        this.icontainer_0 = new Container();
        ComponentResourceManager manager = new ComponentResourceManager(typeof(FormAdditional));
        this.groupBox1 = new GroupBox();
        this.ServerRegion = new Label();
        this.label118 = new Label();
        this.label28 = new Label();
        this.label112 = new Label();
        this.Label116 = new Label();
        this.label117 = new Label();
        this.ConfigIndex = new Label();
        this.RunTimeline = new Label();
        this.AutoBan = new Label();
        this.label22 = new Label();
        this.RuleIndex = new Label();
        this.label114 = new Label();
        this.label119 = new Label();
        this.label20 = new Label();
        this.InternetCafe = new Label();
        this.label26 = new Label();
        this.AutoAccount = new Label();
        this.label111 = new Label();
        this.label44 = new Label();
        this.label115 = new Label();
        this.label23 = new Label();
        this.label113 = new Label();
        this.label17 = new Label();
        this.label43 = new Label();
        this.LocalAddress = new Label();
        this.ServerVersion = new Label();
        this.label25 = new Label();
        this.timer_0 = new Timer(this.icontainer_0);
        this.groupBox1.SuspendLayout();
        base.SuspendLayout();
        this.groupBox1.BackColor = Color.Transparent;
        this.groupBox1.Controls.Add(this.ServerRegion);
        this.groupBox1.Controls.Add(this.label118);
        this.groupBox1.Controls.Add(this.label28);
        this.groupBox1.Controls.Add(this.label112);
        this.groupBox1.Controls.Add(this.Label116);
        this.groupBox1.Controls.Add(this.label117);
        this.groupBox1.Controls.Add(this.ConfigIndex);
        this.groupBox1.Controls.Add(this.RunTimeline);
        this.groupBox1.Controls.Add(this.AutoBan);
        this.groupBox1.Controls.Add(this.label22);
        this.groupBox1.Controls.Add(this.RuleIndex);
        this.groupBox1.Controls.Add(this.label114);
        this.groupBox1.Controls.Add(this.label119);
        this.groupBox1.Controls.Add(this.label20);
        this.groupBox1.Controls.Add(this.InternetCafe);
        this.groupBox1.Controls.Add(this.label26);
        this.groupBox1.Controls.Add(this.AutoAccount);
        this.groupBox1.Controls.Add(this.label111);
        this.groupBox1.Controls.Add(this.label44);
        this.groupBox1.Controls.Add(this.label115);
        this.groupBox1.Controls.Add(this.label23);
        this.groupBox1.Controls.Add(this.label113);
        this.groupBox1.Controls.Add(this.label17);
        this.groupBox1.Controls.Add(this.label43);
        this.groupBox1.Controls.Add(this.LocalAddress);
        this.groupBox1.Controls.Add(this.ServerVersion);
        this.groupBox1.Controls.Add(this.label25);
        this.groupBox1.FlatStyle = FlatStyle.Flat;
        this.groupBox1.Font = new Font("Roboto Slab", 8f);
        this.groupBox1.ForeColor = Color.White;
        this.groupBox1.Location = new Point(15, 9);
        this.groupBox1.Name = "groupBox1";
        this.groupBox1.Size = new Size(390, 0x126);
        this.groupBox1.TabIndex = 90;
        this.groupBox1.TabStop = false;
        this.groupBox1.Text = "Additional Information";
        this.ServerRegion.AutoSize = true;
        this.ServerRegion.Font = new Font("Roboto Slab", 10f);
        this.ServerRegion.ForeColor = Color.Silver;
        this.ServerRegion.Location = new Point(0xda, 0x39);
        this.ServerRegion.Name = "ServerRegion";
        this.ServerRegion.Size = new Size(0x3e, 0x13);
        this.ServerRegion.TabIndex = 0x57;
        this.ServerRegion.Text = "Nations";
        this.label118.AutoSize = true;
        this.label118.Font = new Font("Roboto Slab", 10f);
        this.label118.ForeColor = Color.Silver;
        this.label118.Location = new Point(0x11, 0x39);
        this.label118.Name = "label118";
        this.label118.Size = new Size(0x68, 0x13);
        this.label118.TabIndex = 0x55;
        this.label118.Text = "Server Region";
        this.label28.AutoSize = true;
        this.label28.Font = new Font("Roboto Slab", 10f);
        this.label28.ForeColor = Color.Silver;
        this.label28.Location = new Point(0xca, 0x39);
        this.label28.Name = "label28";
        this.label28.Size = new Size(12, 0x13);
        this.label28.TabIndex = 0x56;
        this.label28.Text = ":";
        this.label112.AutoSize = true;
        this.label112.Font = new Font("Roboto Slab", 10f);
        this.label112.ForeColor = Color.Silver;
        this.label112.Location = new Point(0x11, 0x55);
        this.label112.Name = "label112";
        this.label112.Size = new Size(0x66, 0x13);
        this.label112.TabIndex = 0x2b;
        this.label112.Text = "Local Address";
        this.Label116.AutoSize = true;
        this.Label116.Font = new Font("Roboto Slab", 10f);
        this.Label116.ForeColor = Color.Silver;
        this.Label116.Location = new Point(0x11, 0xc5);
        this.Label116.Name = "Label116";
        this.Label116.Size = new Size(0x76, 0x13);
        this.Label116.TabIndex = 0x4f;
        this.Label116.Text = "Internet PC Cafe";
        this.label117.AutoSize = true;
        this.label117.Font = new Font("Roboto Slab", 10f);
        this.label117.ForeColor = Color.Silver;
        this.label117.Location = new Point(0x11, 0xe1);
        this.label117.Name = "label117";
        this.label117.Size = new Size(0x65, 0x13);
        this.label117.TabIndex = 0x34;
        this.label117.Text = "Auto Account";
        this.ConfigIndex.AutoSize = true;
        this.ConfigIndex.Font = new Font("Roboto Slab", 10f);
        this.ConfigIndex.ForeColor = Color.Silver;
        this.ConfigIndex.Location = new Point(0xda, 0x8d);
        this.ConfigIndex.Name = "ConfigIndex";
        this.ConfigIndex.Size = new Size(15, 0x13);
        this.ConfigIndex.TabIndex = 0x48;
        this.ConfigIndex.Text = "1";
        this.RunTimeline.AutoSize = true;
        this.RunTimeline.Font = new Font("Roboto Slab", 10f);
        this.RunTimeline.ForeColor = Color.Silver;
        this.RunTimeline.Location = new Point(0xda, 0x71);
        this.RunTimeline.Name = "RunTimeline";
        this.RunTimeline.Size = new Size(0x29, 0x13);
        this.RunTimeline.TabIndex = 70;
        this.RunTimeline.Text = "2000";
        this.AutoBan.AutoSize = true;
        this.AutoBan.Font = new Font("Roboto Slab", 10f);
        this.AutoBan.ForeColor = Color.Silver;
        this.AutoBan.Location = new Point(0xda, 0xfd);
        this.AutoBan.Name = "AutoBan";
        this.AutoBan.Size = new Size(0x3f, 0x13);
        this.AutoBan.TabIndex = 0x54;
        this.AutoBan.Text = "Enabled";
        this.label22.AutoSize = true;
        this.label22.Font = new Font("Roboto Slab", 10f);
        this.label22.ForeColor = Color.Silver;
        this.label22.Location = new Point(0xca, 0x8d);
        this.label22.Name = "label22";
        this.label22.Size = new Size(12, 0x13);
        this.label22.TabIndex = 60;
        this.label22.Text = ":";
        this.RuleIndex.AutoSize = true;
        this.RuleIndex.Font = new Font("Roboto Slab", 10f);
        this.RuleIndex.ForeColor = Color.Silver;
        this.RuleIndex.Location = new Point(0xda, 0xa9);
        this.RuleIndex.Name = "RuleIndex";
        this.RuleIndex.Size = new Size(0x3f, 0x13);
        this.RuleIndex.TabIndex = 0x49;
        this.RuleIndex.Text = "Enabled";
        this.label114.AutoSize = true;
        this.label114.Font = new Font("Roboto Slab", 10f);
        this.label114.ForeColor = Color.Silver;
        this.label114.Location = new Point(0x11, 0x8d);
        this.label114.Name = "label114";
        this.label114.Size = new Size(0x5e, 0x13);
        this.label114.TabIndex = 0x30;
        this.label114.Text = "Config Index";
        this.label119.AutoSize = true;
        this.label119.Font = new Font("Roboto Slab", 10f);
        this.label119.ForeColor = Color.Silver;
        this.label119.Location = new Point(0x11, 0xfd);
        this.label119.Name = "label119";
        this.label119.Size = new Size(0x7b, 0x13);
        this.label119.TabIndex = 80;
        this.label119.Text = "Auto Ban System";
        this.label20.AutoSize = true;
        this.label20.Font = new Font("Roboto Slab", 10f);
        this.label20.ForeColor = Color.Silver;
        this.label20.Location = new Point(0xca, 0x71);
        this.label20.Name = "label20";
        this.label20.Size = new Size(12, 0x13);
        this.label20.TabIndex = 0x3a;
        this.label20.Text = ":";
        this.InternetCafe.AutoSize = true;
        this.InternetCafe.Font = new Font("Roboto Slab", 10f);
        this.InternetCafe.ForeColor = Color.Silver;
        this.InternetCafe.Location = new Point(0xda, 0xc5);
        this.InternetCafe.Name = "InternetCafe";
        this.InternetCafe.Size = new Size(0x3f, 0x13);
        this.InternetCafe.TabIndex = 0x53;
        this.InternetCafe.Text = "Enabled";
        this.label26.AutoSize = true;
        this.label26.Font = new Font("Roboto Slab", 10f);
        this.label26.ForeColor = Color.Silver;
        this.label26.Location = new Point(0xca, 0xa9);
        this.label26.Name = "label26";
        this.label26.Size = new Size(12, 0x13);
        this.label26.TabIndex = 0x40;
        this.label26.Text = ":";
        this.AutoAccount.AutoSize = true;
        this.AutoAccount.Font = new Font("Roboto Slab", 10f);
        this.AutoAccount.ForeColor = Color.Silver;
        this.AutoAccount.Location = new Point(0xda, 0xe1);
        this.AutoAccount.Name = "AutoAccount";
        this.AutoAccount.Size = new Size(0x43, 0x13);
        this.AutoAccount.TabIndex = 0x4c;
        this.AutoAccount.Text = "Disabled";
        this.label111.AutoSize = true;
        this.label111.Font = new Font("Roboto Slab", 10f);
        this.label111.ForeColor = Color.Silver;
        this.label111.Location = new Point(0x11, 0x1d);
        this.label111.Name = "label111";
        this.label111.Size = new Size(110, 0x13);
        this.label111.TabIndex = 50;
        this.label111.Text = "Server Version";
        this.label44.AutoSize = true;
        this.label44.Font = new Font("Roboto Slab", 10f);
        this.label44.ForeColor = Color.Silver;
        this.label44.Location = new Point(0xca, 0xc5);
        this.label44.Name = "label44";
        this.label44.Size = new Size(12, 0x13);
        this.label44.TabIndex = 0x51;
        this.label44.Text = ":";
        this.label115.AutoSize = true;
        this.label115.Font = new Font("Roboto Slab", 10f);
        this.label115.ForeColor = Color.Silver;
        this.label115.Location = new Point(0x11, 0xa9);
        this.label115.Name = "label115";
        this.label115.Size = new Size(0x7e, 0x13);
        this.label115.TabIndex = 0x31;
        this.label115.Text = "Tournament Rule";
        this.label23.AutoSize = true;
        this.label23.Font = new Font("Roboto Slab", 10f);
        this.label23.ForeColor = Color.Silver;
        this.label23.Location = new Point(0xca, 0xe1);
        this.label23.Name = "label23";
        this.label23.Size = new Size(12, 0x13);
        this.label23.TabIndex = 0x3d;
        this.label23.Text = ":";
        this.label113.AutoSize = true;
        this.label113.Font = new Font("Roboto Slab", 10f);
        this.label113.ForeColor = Color.Silver;
        this.label113.Location = new Point(0x11, 0x71);
        this.label113.Name = "label113";
        this.label113.Size = new Size(100, 0x13);
        this.label113.TabIndex = 0x2e;
        this.label113.Text = "Run Timeline";
        this.label17.AutoSize = true;
        this.label17.Font = new Font("Roboto Slab", 10f);
        this.label17.ForeColor = Color.Silver;
        this.label17.Location = new Point(0xca, 0x55);
        this.label17.Name = "label17";
        this.label17.Size = new Size(12, 0x13);
        this.label17.TabIndex = 0x37;
        this.label17.Text = ":";
        this.label43.AutoSize = true;
        this.label43.Font = new Font("Roboto Slab", 10f);
        this.label43.ForeColor = Color.Silver;
        this.label43.Location = new Point(0xca, 0xfd);
        this.label43.Name = "label43";
        this.label43.Size = new Size(12, 0x13);
        this.label43.TabIndex = 0x52;
        this.label43.Text = ":";
        this.LocalAddress.AutoSize = true;
        this.LocalAddress.Font = new Font("Roboto Slab", 10f);
        this.LocalAddress.ForeColor = Color.Silver;
        this.LocalAddress.Location = new Point(0xda, 0x55);
        this.LocalAddress.Name = "LocalAddress";
        this.LocalAddress.Size = new Size(50, 0x13);
        this.LocalAddress.TabIndex = 0x43;
        this.LocalAddress.Text = "0.0.0.0";
        this.ServerVersion.AutoSize = true;
        this.ServerVersion.Font = new Font("Roboto Slab", 10f);
        this.ServerVersion.ForeColor = Color.Silver;
        this.ServerVersion.Location = new Point(0xda, 0x1d);
        this.ServerVersion.Name = "ServerVersion";
        this.ServerVersion.Size = new Size(0x26, 0x13);
        this.ServerVersion.TabIndex = 0x4a;
        this.ServerVersion.Text = "V3.0";
        this.label25.AutoSize = true;
        this.label25.Font = new Font("Roboto Slab", 10f);
        this.label25.ForeColor = Color.Silver;
        this.label25.Location = new Point(0xca, 0x1d);
        this.label25.Name = "label25";
        this.label25.Size = new Size(12, 0x13);
        this.label25.TabIndex = 0x3f;
        this.label25.Text = ":";
        this.timer_0.Interval = 0x3e8;
        this.timer_0.Tick += new EventHandler(this.timer_0_Tick);
        base.AutoScaleDimensions = new SizeF(7f, 15f);
        base.AutoScaleMode = AutoScaleMode.Font;
        this.BackColor = Color.FromArgb(0x2e, 0x33, 0x49);
        base.ClientSize = new Size(420, 0x139);
        base.Controls.Add(this.groupBox1);
        this.Font = new Font("Roboto Slab", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
        base.FormBorderStyle = FormBorderStyle.None;
        base.Icon = (Icon) manager.GetObject("$this.Icon");
        base.Name = "FormAdditional";
        this.Text = "FormAdditional";
        base.Load += new EventHandler(this.FormAdditional_Load);
        this.groupBox1.ResumeLayout(false);
        this.groupBox1.PerformLayout();
        base.ResumeLayout(false);
    }

    override void Form.Dispose(bool disposing)
    {
        if (disposing && (this.icontainer_0 != null))
        {
            this.icontainer_0.Dispose();
        }
        base.Dispose(disposing);
    }

    private void timer_0_Tick(object sender, EventArgs e)
    {
        this.ServerVersion.Text = GClass9.string_14;
        this.ServerRegion.Text = GClass9.string_15;
        this.LocalAddress.Text = GClass9.string_16;
        this.RunTimeline.Text = GClass9.string_17;
        this.ConfigIndex.Text = GClass9.string_18;
        this.RuleIndex.Text = GClass9.string_19;
        this.RuleIndex.ForeColor = GClass9.string_19.Equals("Enabled") ? ColorUtil.Green : (GClass9.string_19.Equals("Disabled") ? ColorUtil.Yellow : ColorUtil.Silver);
        this.InternetCafe.Text = GClass9.string_20;
        this.InternetCafe.ForeColor = GClass9.string_20.Equals("Enabled") ? ColorUtil.Green : (GClass9.string_20.Equals("Disabled") ? ColorUtil.Yellow : ColorUtil.Silver);
        this.AutoAccount.Text = GClass9.string_21;
        this.AutoAccount.ForeColor = GClass9.string_21.Equals("Enabled") ? ColorUtil.Green : (GClass9.string_21.Equals("Disabled") ? ColorUtil.Yellow : ColorUtil.Silver);
        this.AutoBan.Text = GClass9.string_22;
        this.AutoBan.ForeColor = GClass9.string_22.Equals("Enabled") ? ColorUtil.Green : (GClass9.string_22.Equals("Disabled") ? ColorUtil.Yellow : ColorUtil.Silver);
    }
}

