using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000699 RID: 1689
	internal enum IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x0400221B RID: 8731
		IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
